### ISSUE TITLE
DoSelect Platform REST APIs inaccessible via Django shell plus

### ISSUE THREAD

**Issue by jojurajan** [doselect/api-platform-support#2]
#### API Platform component

Platform APIs (REST)

#### Description

DoSelect APIs are inaccessible via requests using Django shell plus. The API that I am trying out is User Submissions API - `https://api.doselect.com/platform/v1/problem/<problem_id>/submission/<student_email>`
##### Steps to reproduce

1. Use the following code after replacing the variables.
```
url = 'https://api.doselect.com/platform/v1/problem/<problem_slug>/submission/<student_email>'
headers = {
    'DoSelect-Api-Key': '<api_key>',
    'DoSelect-Api-Secret': '<api_secret>'
}
requests.get(url, headers=headers)
```
2. The console gets stuck on the response.

#### Context (environment)

The user submissions API is to be used as a fallback in case the webhooks fail to be ingested by our server.

**Comment by hemil** [comment]
@jojurajan I tried to reproduce it using the aforementioned steps, but wasn't able to.
The API is working fine, when being called from the shell_plus as well as from curl.

Are you on any VPNs or a company network?
Can you try reproducing it when the laptop is connected to a mobile hotspot?

**Comment by jojurajan** [comment]
@hemil The APIs work fine via the shell_plus. It was an iTerm sessions issue which had affected other applications too. Sorry for the trouble.
