### ISSUE TITLE
Code revision history API documentation.

### ISSUE THREAD

**Issue by jojurajan** [doselect/api-platform-support#3]
#### API Platform component

Platform APIs

#### Description

The code revision history data is available on the Embed. Could you add the details regarding accessing it via the Platform APIs?

**Comment by hemil** [comment]
@jojurajan We currently do not have the APIs for this. We have added it to the roadmap and this should be available by the end of next week

**Comment by hemil** [comment]
Docs: https://docs.doselect.com/#get-solution-revision
