### ISSUE TITLE
Problem Update API returns error on valid PATCH payload.

### ISSUE THREAD

**Issue by jojurajan** [doselect/api-platform-support#4]
#### API Platform component

Platform APIs (REST)

#### Description

The DoSelect Problem update API is returning `"Invalid request body."` on trying to update the tags/description and/or name of the problem.

##### Steps to reproduce

1. Use the following code after replacing the appropriate values. `curl -X PATCH \
  https://api.doselect.com/platform/v1/problem/<problem_slug> \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'doselect-api-key: <do-select-api-key>' \
  -H 'doselect-api-secret: <do-select-api-secret>' \
  -H 'postman-token: 3d7ddd6d-c683-859f-45e7-ba540a051011' \
  -d '{"name": "hello_world"}'`
2. The response returned is an error instead of problem data.

**Comment by hemil** [comment]
@jojurajan This should be fixed now. Please check

**Comment by jojurajan** [comment]
Yes. This is fixed for now.
