### ISSUE TITLE
Clone Problem API - `DSC` type questions don't clone the data sets

### ISSUE THREAD

**Issue by jojurajan** [doselect/api-platform-support#5]
#### API Platform component

Platform APIs(REST)

#### Description

While cloning problems of  type `DSC`, the datasets are not getting copied to the new problem.

##### Steps to reproduce

1. Use the following code after replacing appropriate values. Use a Data Science problem slug which has data sets in it for the request
`curl -X POST \
  https://api.doselect.com/platform/v1/problem/<problem_slug>/clone \
  -H 'cache-control: no-cache' \
  -H 'doselect-api-key: <do-select-api-key>' \
  -H 'doselect-api-secret: <do-select-api-secret>' \
  -H 'postman-token: ce140bb0-0c28-6a65-32bf-9209c4411376'`
2. In the response, we can see that the attachments are empty 
`"attachments": [{"type": "trainingDataSet","url": ""},{"type": "sampleDataSet","url": ""},{"type": "evalDataSet","url": ""}]`

**Comment by hemil** [comment]
@jojurajan checking

**Comment by hemil** [comment]
@jojurajan It was an edgecase for the datascience type problems in the cloning flow. This has been fixed now
