### ISSUE TITLE
DoSelect Update API deletes data from keys not present in the PATCH payload.

### ISSUE THREAD

**Issue by jojurajan** [doselect/api-platform-support#6]
#### API Platform component

Platform APIs (REST)

#### Description

The DoSelect Update API deletes data from attributes not specified in the PATCH payload.

##### Steps to reproduce

1. Use the following code after replacing appropriate values. Use a Data Science problem slug which has description, stubs in it for the request
```
curl -X PATCH  https://api.doselect.com/platform/v1/problem/<problem_slug>  -H 'cache-control: no-cache'  -H 'cache-control: no-cache' \ -H 'doselect-api-key: <do-select-api-key>' \ -H 'doselect-api-secret: <do-select-api-secret>' -d '{ "tags": [ "randomTag" ] }'
```
2. In the response, we can see that the description comes as empty

**Comment by hemil** [comment]
@joju We're pushing a fix for this. Will let you know once it is deployed

**Comment by hemil** [comment]
@jojurajan This has been fixed

**Comment by jojurajan** [comment]
The update API still deletes data. The stubs and sample solutions get deleted on updating the problem description.

**Comment by hemil** [comment]
@jojurajan This has been fixed...Please check
